version: '3.8'

services:
  django:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: 'django'
    volumes:
      - ./backend:/app/
    depends_on:
      - transcendence_pg
    env_file:
      - .env
    networks:
      - transcendence
    restart: on-failure

  # Daphne container for the websockets
  daphne:
    build:
      context: ./backend/
      dockerfile: Dockerfile.daphne
    container_name: 'daphne'
    volumes:
      - ./backend:/app/
    depends_on:
      - transcendence_pg
      - redis
    env_file:
      - .env
    ports:
      - "${DJANGO_WS_PORT}:8001"
    networks:
      - transcendence
    restart: on-failure

  # Redis container for the websockets
  redis:
    image: "redis:7.2.5-alpine"
    container_name: "redis"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    networks:
      - transcendence

  transcendence_nginx:
    image: nginx
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - django
    networks:
      - transcendence

  transcendence_pg:
    image: postgres
    container_name: 'transcendence_pg'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
  postgres_data:
